# Generated by Django 3.1.6 on 2021-06-02 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ukmunicipality', models.TextField(default='')),
                ('yybaranggay', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zflname', models.TextField(default='')),
                ('znaddress', models.TextField(default='')),
                ('zpngender', models.TextField(default='')),
                ('zpnumber', models.TextField(default='')),
                ('zvphilhealth', models.TextField(default='')),
                ('zrmbirthday', models.TextField(default='')),
                ('municipality', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='RICList.municipality')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpbrandname', models.TextField(default='')),
                ('vr1stdose2nd', models.TextField(default='')),
                ('vadategiven', models.DateTimeField(default='')),
                ('vftestingcenter', models.TextField(default='')),
                ('personal_info', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='RICList.personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='Comorbidities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cccomorbidity', models.TextField(default='')),
                ('callergies', models.TextField(default='')),
                ('personal_info', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='RICList.personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zfccategories', models.TextField(default='')),
                ('personal_info', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='RICList.personal_info')),
            ],
        ),
    ]
