# Generated by Django 3.1.6 on 2021-06-26 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ukmunicipality', models.TextField(default='')),
                ('yybaranggay', models.TextField(default='')),
                ('xxregion', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zflname', models.TextField(default='')),
                ('znaddress', models.TextField(default='')),
                ('rremail', models.TextField(default='')),
                ('zvphil', models.TextField(default='')),
                ('zpnumber', models.TextField(default='')),
                ('zemerg', models.TextField(default='')),
                ('zfccategories', models.TextField(default='')),
                ('hhrelat', models.TextField(default='')),
                ('rmgender', models.TextField(default='')),
                ('zbirth', models.TextField(default='')),
                ('municipality', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='RICList.municipality')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpbrandname', models.TextField(default='')),
                ('vr1stdosedate', models.DateField(default='')),
                ('vr2nddosedate', models.DateField(default='')),
                ('vftestingcenter', models.TextField(default='')),
                ('vaccinator', models.TextField(default='')),
                ('personal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='RICList.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zfcemployed', models.TextField(default='')),
                ('employnst', models.TextField(default='')),
                ('occu', models.TextField(default='')),
                ('employern', models.TextField(default='')),
                ('eaddr', models.TextField(default='')),
                ('personal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='RICList.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Comorbidities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cccomorbidity', models.TextField(default='')),
                ('callergies', models.TextField(default='')),
                ('diagnosedu', models.TextField(default='')),
                ('dicovid', models.TextField(default='')),
                ('datecovid', models.DateField(default='')),
                ('classcovid', models.TextField(default='')),
                ('personal', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='RICList.personal')),
            ],
        ),
    ]
