# Generated by Django 3.1.6 on 2021-05-03 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COVIDList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zflname', models.TextField(default='')),
                ('znaddress', models.TextField(default='')),
                ('zpnumber', models.TextField(default='')),
                ('zrmbirthday', models.TextField(default='')),
                ('zvaccine', models.TextField(default='')),
                ('list', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='RICList.covidlist')),
            ],
        ),
    ]
