# Generated by Django 3.1.6 on 2021-06-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RICList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comorbidities',
            old_name='dicovid',
            new_name='tyallergies',
        ),
        migrations.AddField(
            model_name='comorbidities',
            name='tycomorbidity',
            field=models.TextField(default=''),
        ),
    ]
