# Generated by Django 3.1.6 on 2021-06-27 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RICList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comorbidities',
            name='personal',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='RICList.personal'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='personal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RICList.personal'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='municipality',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RICList.municipality'),
        ),
        migrations.AlterField(
            model_name='vaccination_details',
            name='personal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RICList.personal'),
        ),
    ]
