# Generated by Django 3.1.6 on 2021-06-25 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RICList', '0002_auto_20210625_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comorbidities',
            old_name='tyallergies',
            new_name='dicovid',
        ),
        migrations.RemoveField(
            model_name='comorbidities',
            name='tycomorbidity',
        ),
    ]
