# Generated by Django 3.1.6 on 2021-06-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RICList', '0003_auto_20210625_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='zresult',
            field=models.TextField(default=''),
        ),
    ]
