# Generated by Django 3.1.6 on 2021-06-26 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RICList', '0004_personal_info_zresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_info',
            name='zresult',
        ),
    ]
